### ISSUE TITLE
心跳检测失败动作增加选项

### ISSUE THREAD

**Issue by tme1946** [819548945/WebDisplay#1]
需求：电脑关机后，切换显示时钟app

功能：
在”心跳检查失败动作“中，增加选项”打开app“，内容为手机app列表

效果：
当心跳检测失败后，打开指定app，同时后台持续进行心跳检测
当心跳检测再次成功后，切换会原页面

**Comment by 819548945** [comment]
这种功能是无法现实的，后台应用必须经过手动操作才能切换回前台
